[project]
name = "scrapper"
version = "0.1.0"
description = "Job scrapper using Google Custom Search API"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "requests>=2.32.5",
    "streamlit>=1.51.0",
]
